export const SETCURSOS = "SETCURSOS";
export const SETCURSOSPAGINACAO = "SETCURSOSPAGINACAO";
export const SETPAGINACAO = "SETPAGINACAO";
export const SETSEARCH = "SETSEARCH";
export const SETCURSO = "SETCURSO";
export const SETLOADING = "SETLOADING";

export const SETCATEGORIAS = "SETCATEGORIAS";
export const SETCATEGORIA = "SETCATEGORIA";
export const CLEARCATEGORIA = "CLEARCATEGORIA";
export const SETLOADINGCATEGORIA = "SETLOADINGCATEGORIA";

export const SETAULA = "SETAULA";
export const SETHISTORICOAULA = "SETHISTORICOAULA";
