export const SETCLASSCOLORHEADER = "SETCLASSCOLORHEADER";
export const SETMOSTRARCABECALHO = "SETMOSTRARCABECALHO";
export const SETMOSTRARNOTIFICACAO = "SETMOSTRARNOTIFICACAO";
export const SETMENU = "SETMENU";
