export const SETPROVA = "SETPROVA";
export const SETPROVAID = "SETPROVAID";
export const SETQUESTIONARIO = "SETQUESTIONARIO";
export const SETQUESTIONARIOID = "SETQUESTIONARIOID";
export const SETPROVAS = "SETPROVAS";
export const SETLOADING = "SETLOADING";
