name: CI

on:
  push: {branches: master}
  
  workflow_dispatch:

env:
  BUCKET: classic.efbclass.com

jobs:
  job_1:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: npm install
    - run: npm run build
    # run: npm test
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Upload files to bucket
      run: gsutil -m rsync -R ./ gs://"$BUCKET"

    - name: Allow public access
      run: gsutil -m acl ch -R -u AllUsers:R gs://"$BUCKET"


